### PR TITLE
fix/upload-url-generation

### PR DESCRIPTION
**Pull request by sraver**
Fix the URL generation for uploading a file when the app should not use a proxy

### CODE REVIEW

**Comment by AlexMenor** [comment]
Hi @sraver, I believe we had an env variable for this

**Comment by sraver** [comment]
> Hi @sraver, I believe we had an env variable for this

Nice, I added the check into the code so it works as it seems would be expected.

**Comment by AlexMenor** [comment]
@sraver can we avoid relying on the host somehow? Even if its including env variables.

**Comment by sraver** [comment]
> @sraver can we avoid relying on the host somehow? Even if its including env variables.

I think we could, maybe checking the NODE_ENV, but I didn't want to change much the original logic cos I didn't know the idea or purpose behind.

@sg-gs You think we can switch the host checking for the env??

**Comment by sraver** [comment]
Also, on another note. I added the same checking on the construction of the download URLs, otherwise on local the downloads were not working for me.

Those: https://github.com/internxt/drive-web/pull/334/files#diff-262c5a71d08e190d6ade5e990252eb1421ba2cabd7a2a524626956ff75a1ac0aR186-R190

**Comment by AlexMenor** [comment]
> > @sraver can we avoid relying on the host somehow? Even if its including env variables.
> 
> I think we could, maybe checking the NODE_ENV, but I didn't want to change much the original logic cos I didn't know the idea or purpose behind.
> 
> @sg-gs You think we can switch the host checking for the env??

I was thinking that the logic behind using them should not be in the code, and rather just be configurable so the source of truth are just the env variables

**Pull request closed without merging**
