### PR TITLE
[PB-1425] feature/Add ability to update the email on Drive web

### PR DESCRIPTION
**Pull request by CandelR**
- Added ability to change user email

⚠️ Notes:
The following RPs need to be merged to test this task:
- https://github.com/internxt/drive-server-wip/pull/243
- https://github.com/internxt/sdk/pull/181
- https://github.com/internxt/drive-server-wip/pull/255

### CODE REVIEW

**Comment by claell** [comment]
Interesting, this seems to be the PR relevant for the feature already listed as available on https://help.internxt.com/en/articles/8290565-internxt-public-roadmap-2023.

I was told yesterday by support that this feature is "about to be released". Is that correct?

**Review by rafijv — APPROVED** [review]

**Comment by edisonjpadilla** [comment]
it seems the new email is hardcoded and it isn't taking from the query params

Screenshot 2024-01-02 at 1 16 39 PM

**Comment by CandelR** [comment]
> it seems the new email is hardcoded and it isn't taking from the query params
> 
> Screenshot 2024-01-02 at 1 16 39 PM

@edisonjpadilla you are testing on production URL, need to test with the preview domain

**Review by rafijv — APPROVED** [review]

**Comment by claell** [comment]
@CandelR Nice to see this feature implemented! Thanks! Hope the public communication can improve in the future.

**Pull request merged**
